### ISSUE TITLE
Blank page after authorization

### ISSUE THREAD

**Issue by jcarruthers** [yegor256/s3auth#346]
I set up s3auth, following the instructions.

When I navigate to my site, playbook.handshq.com, I get the pop-up requesting a username and password, which I enter, but after I just get the message in the browser status bar saying 'waiting for playbook.handshq.com' and nothing happens.

**Comment by jcarruthers** [comment]
Resolved this - it was an issue with Cloudflare attempting to serve from CDN. I bypassed the CDN and it worked.

**Comment by 0crat** [comment]
Job `gh:yegor256/s3auth#346` was not in scope

**Comment by rth** [comment]
Thanks for opening this issue. Just run into this as well, definitely not easy to find the root cause. For future reference, loading e.g. the `.htpasswd` with,
```
wget http://subdomain.domain.com/.htpasswd
```
with mis-configured CloudFlare produces,
```
Cookie coming from subdomain.domain.com attempted to set domain to domain.eu
Length: unspecified [text/plain]
Saving to: ‘.htpasswd’

.htpasswd                                 [ <=>                                                                         ]      10  --.-KB/s    in 0s      

2017-09-11 17:05:45 (228 KB/s) - Read error at byte 10 (Success).Retrying.
```
(these retries is why the browser keeps saying "waiting for response" without returning anything..)

Enabling CloudFlare CND bypass does fix it, as reported above.
